#define MESSAGE_Q   "/MESSAGE_Q_LOGGER"
#define BUFFER_SIZE 4096
#define MAX_QUE_MSGSIZE 10
#define MESSAGE_PRIORITY  30
#define MESSAGE_PRIORITY_INIT 25
#define MESSAGE_PRIORITY_ERR 20

#define TEMPERATURE_MESSAGE_Q   "/MESSAGE_Q_TEMPERATURE"
#define LIGHT_MESSAGE_Q   "/MESSAGE_Q_LIGHT"
#define MESSAGE_Q_ERR   "/MESSAGE_Q_ERROR"
